@startuml
actor User
participant AuthController
participant AuthService
participant UserRepository
participant JwtProvider
participant JwtFilter
participant SecurityContextHolder
participant Authentication
participant GlobalExceptionHandler
participant ApiResponseDto

database DB

== login == 

User -> AuthController : POST api/auth/login login(AuthRequestDto req))

alt email or password is empty
  AuthController --> GlobalExceptionHandler : throw ValidationException
  GlobalExceptionHandler --> User : 400 "ERROR" ApiResponseDto<String> "メールアドレス、パスワードの両方をご入力ください。"

else email is not valid
  AuthController --> GlobalExceptionHandler : throw ValidationException
  GlobalExceptionHandler --> User : 400 "ERROR" ApiResponseDto<String> "正しいメールアドレスをご入力ください。"

else OK
  AuthController -> AuthService : authenticate(email, password)
  AuthService -> UserRepository : findByEmail(email)
  UserRepository -> DB : SELECT * FROM users WHERE email=?
  DB --> UserRepository : user data
  UserRepository --> AuthService :user

  alt user not found
    AuthService --> AuthController : Unauthorized
    AuthController --> GlobalExceptionHandler : throw AuthenticationException
    GlobalExceptionHandler --> User : 401 "ERROR" ApiResponseDto<String> "アカウントが確認出来ませんでした。正しいメールアドレスとパスワードをご入力ください。"

  else password does not match
    AuthService --> AuthController : Unauthorized
    AuthController --> GlobalExceptionHandler : throw AuthenticationException
    GlobalExceptionHandler --> User : 401 "ERROR" ApiResponseDto<String> "アカウントが確認出来ませんでした。正しいメールアドレスとパスワードをご入力ください。"
    
  else OK
    AuthService -> JwtProvider : genetateToken(id)
    JwtProvider --> AuthService : token
    AuthService --> AuthController : token
    AuthController --> User : 200 "SUCCESS" + ApiResponseDto<String> 
  end
end

== logout ==

User -> Frontend : logout click
Frontend -> Frontend : remove JWT
Frontend --> User : logout success

@enduml